language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

addons:
  hosts:
    - redis

services:
  - redis-server

branches:
  only:
    - master
    - develop

before_install:
  - pecl channel-update pecl.php.net
  - printf 'yes\nno\nyes\nno\nno\nno\nno\n' | pecl install swoole
  - printf 'no\nno\n' | pecl install redis
  - export APP_NAME=logger-server
  - export REDIS_SERVER_HOST=redis
  - php -m
  - composer install

script:
  - php index.php start -d
  - sleep 5
  - ./vendor/bin/phpunit