language: php

php:
  - '7.1'
  - '7.2'

addons:
  hosts:
    - redis

services:
  - redis-server

branches:
  only:
    - master
    - develop

before_install:
  - pecl channel-update pecl.php.net
  - printf 'yes\nno\nyes\nno\nno\nno\nno\n' | pecl install swoole
  - printf 'no\nno\n' | pecl install redis
  - echo "extension = swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "APP_NAME=logger-server" > .env
  - echo "REDIS_SERVER_HOST=redis" >> .env
  - composer install

script:
  - php index start -d
  - sleep 5
  - ./vendor/bin/phpunit